exports.todoPage = function (tarefas, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>To do</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1> 
                        To do
                    </h1>
                </header>

                <div class="w3-row">
                    <form class="w3-content w3-container" method="POST">
                        <input class="w3-input w3-round" type="hidden" name="id" value="${tarefas.length + 1}">
                        <input class="w3-input w3-round" type="hidden" name="estado" value="todo">

                        <fieldset>
                            <legend>O quê?</legend>
                            <input class="w3-input w3-round" type="text" name="nome">
                        </fieldset>

                        <fieldset>
                            <legend>Quem?</legend>
                            <input class="w3-input w3-round" type="text" name="quem">
                        </fieldset>

                        <fieldset>
                            <legend>Para quando?</legend>
                            <input class="w3-input w3-round" type="date"name="quando">
                        </fieldset>  
                        
                        <button class="w3-btn w3-teal w3-mb-2" type="submit">Add</button>
                    </form>
                </div>
        
                <div class="w3-row">
                    <div class="w3-half w3-container">
                        <div class="w3-card w3-khaki w3-center"> 
                            <h2> Tarefas por fazer </h3>
                        </div>

                        <table class="w3-table-all">
                           <tr>
                               <th>Nome Tarefa</th><th>Quem?</th><th>Para Quando?</th> 
                               <th>Done</th>
                           </tr>
                            `
    
    for (let i in tarefas) {
        var t = tarefas[i]
        if (t.estado == "todo") {
            pagHTML += `
               <tr>
                   <td> ${t.nome} </td>          
                   <td> ${t.quem} </td>          
                   <td> ${t.quando} </td>          
                   <td> 
                       <form method="POST"> 
                           <input type="hidden" name="id" value="${t.id}">
                           <input type="hidden" name="nome" value="${t.nome}">
                           <input type="hidden" name="quem" value="${t.quem}">
                           <input type="hidden" name="quando" value="${t.quando}">
                           <input class="w3-check" type="checkbox" name="estado" value="done">
                           <button class="w3-btn w3-teal w3-mb-2" type="submit">X</button>
                        </form>
                   </td>          
                </tr>
            `                                          
        }
    }                                              
    pagHTML += `                                   
                        </table>
                    </div>
                    <div class="w3-half w3-container">
                        <div class="w3-card w3-red w3-center"> 
                            <h2> Tarefas feitas </h3>
                        </div>
                        <table class="w3-table-all">
                            <tr>
                                <th>Nome Tarefa</th><th>Quem?</th>
                            </tr>
    `
    
    for (let i in tarefas) {
        var t = tarefas[i]
        if (t.estado == "done") {
               pagHTML += `
                    <tr>
                        <td> ${t.nome} </td>          
                        <td> ${t.quem} </td>          
                    </tr>
               ` 
        }
    }

    pagHTML += `
                        </table>
                    </div> 
                </div>

                <footer class="w3-container w3-teal">
                    <h5>Generated by RPCW2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>

        </div>
        </body>
        </html>
    `
    return pagHTML
}